### ISSUE TITLE
electrum 4.4.0-4.4.2 not working with jade-diy bitcoin app (pre-2.1): no sig for <compressed_pubkey>

### ISSUE THREAD

**Issue by sandman21vs** [Blockstream/Jade#73]
the same problem is happening on the link that I will send below, in the electrum wallet jade cannot make transactions, according to the electrum staff it is because it is probably running the old version of something related to bitcoin ,
I hope this bug is fixed (and also the bug that prevents using jade diy on windows with the green wallet app)
https://github.com/spesmilo/electrum/issues/8365

**Comment by sandman21vs** [comment]
![image](https://github.com/Blockstream/Jade/assets/31391404/2878d43c-8b8b-4659-a7d4-18fb2bbc577d)

**Comment by JamieDriver** [comment]
This is a regression issue with electrum wallet, and was resolved by commit: https://github.com/spesmilo/electrum/commit/2752cd21834f81af4b71b80277191271f98f6518

See: https://github.com/spesmilo/electrum/issues/8463

My understanding is that it is fixed in: https://github.com/spesmilo/electrum/releases/tag/4.4.5

**Comment by sandman21vs** [comment]
Thanks, I'm going to compile and test, it looks like this release came out 7 hours ago and it's still not available on the electrum website to download

**Comment by JamieDriver** [comment]
Super - pls close this issue if their fix resolves the problems you are experiencing.
Many Thanks.

**Comment by JamieDriver** [comment]
Is this resolved ?  Can we close ?  Thanks ?

**Comment by JamieDriver** [comment]
Closing due to inactivity.  Believed to be caused by a now-resolved Electrum issue.
